#!/bin/bash

# Please set host/port info
# ADDB Redis-RocksDB
HOST_LIST=( )
HOST_IP_LIST=( ) # for creating redis cluster
PORT_LIST=( )
PORT_LIST_1=( )  # for storing data separately
PORT_LIST_2=( )
NODE_LIST=( 0 1 2 3 4 5 )

## CONSTANT
REDIS_SERVER=redis-server
CONF_PREFIX=redis_tiering

## Get IP
IFS=$'\n' res=(`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`)
IP=${res[0]}

## Directory
CONF_DIR=${ADDB_HOME}/conf
SCRIPT_DIR=${ADDB_HOME}/scripts
LOG_DIR=${ADDB_HOME}/dir/log
RUN_DIR=${ADDB_HOME}/dir/run
DATA_DIR_1=${ADDB_HOME}/dir/ssd1
DATA_DIR_2=${ADDB_HOME}/dir/ssd2

ROCKSDB_DATA_DIR="0:default"

